import React, { useState } from "react";
import PropTypes from "prop-types";
import { useSelector } from "react-redux";
import { useHistory } from "react-router-dom";
import { makeStyles } from "@material-ui/core/styles";
import { Grid, Typography, Button, TextField } from "@material-ui/core";

const useStyles = makeStyles(() => ({
  filterContainer: {
    marginBottom: 25,
  },
}));

const FlightBooking = () => {
  // Assuming Redux state structure: state.flightSearch.bookingDetails
  const bookingData = useSelector((state) => state.flightSearch.bookingDetails);
  
  const [fName, setFName] = useState("");
  const [lName, setLName] = useState("");
  const [email, setEmail] = useState("");
  const [mobile, setMobile] = useState("");
  const [errorFlag, setErrorFlag] = useState(false);
  
  const history = useHistory();
  const classes = useStyles();

  const handleFName = (e) => {
    setFName(e.target.value);
  };

  const handleLName = (e) => {
    setLName(e.target.value);
  };

  const handleEmail = (e) => {
    setEmail(e.target.value);
  };

  const handleMobile = (e) => {
    // Basic number validation could be added here
    setMobile(e.target.value);
  };

  /**
   * @function handleConfirm
   * @description Confirm the booking and navigate if fields are filled
   */
  const handleConfirm = () => {
    if (
      fName.trim().length > 0 &&
      lName.trim().length > 0 &&
      email.trim().length > 0 &&
      mobile.trim().length > 0
    ) {
      setErrorFlag(false);
      // Logic for actual booking API call would go here
      history.push("/confirmation");
    } else {
      setErrorFlag(true);
    }
  };

  return (
    <Grid container spacing={2}> {/* Added spacing for better layout */}
      <Grid item xs={12} className={classes.filterContainer}>
        <Typography variant="h6">
          {`Booking Confirmation for Flight ${bookingData?.result?.airlineName || 'Airline'} (${bookingData?.result?.flightNbr || 'N/A'})`}
        </Typography>
      </Grid>
      
      <Grid item xs={12} md={6} className={classes.filterContainer}>
        <TextField required label="First Name" value={fName} onChange={handleFName} fullWidth className="first_name" />
      </Grid>
      <Grid item xs={12} md={6} className={classes.filterContainer}>
        <TextField required label="Last Name" value={lName} onChange={handleLName} fullWidth className="last_name" />
      </Grid>
      
      <Grid item xs={12} md={6} className={classes.filterContainer}>
        <TextField required label="Email ID" value={email} onChange={handleEmail} fullWidth className="email_id" />
      </Grid>
      <Grid item xs={12} md={6} className={classes.filterContainer}>
        <TextField required label="Mobile Number" value={mobile} onChange={handleMobile} fullWidth className="mobile_number" />
      </Grid>
      
      <Grid item xs={12} md={6} className={classes.filterContainer}>
        <Button variant="contained" color="primary" onClick={handleConfirm} className="confirm_booking">
          Confirm Booking
        </Button>
        {errorFlag && (
          <Typography color="error" style={{ marginTop: '10px' }}>
            All Fields are mandatory
          </Typography>
        )}
      </Grid>
    </Grid>
  );
};

// Removed `classes` from propTypes as it's not passed but generated by hook.
FlightBooking.propTypes = {
  history: PropTypes.object,
}; 

export default FlightBooking;
