import React from "react";
import PropTypes from "prop-types";
import { useHistory } from "react-router-dom";

import { Typography, Button, Grid } from "@material-ui/core";
import { makeStyles } from "@material-ui/core/styles";

const useStyles = makeStyles(() => ({
  button: {
    marginTop: 20, // Increased margin for better separation
  },
  container: {
    textAlign: "center",
    marginTop: "50px", // Center the content on the page
  }
}));

const Confirmation = () => {
  const history = useHistory();
  const classes = useStyles();

  return (
    <Grid container justifyContent="center" className={classes.container}>
      <Grid item xs={12}>
        <Typography
          variant="h5" // Changed variant to h5 for better prominence
          color="textPrimary"
          className="confirmation_message"
          id="confirmation-message"
        >
          {`Thank you for the Booking. Click the below button to return to home page`}
        </Typography>
      </Grid>
      <Grid item xs={12}>
        <Button
          variant="outlined"
          color="primary"
          className={`${classes.button} back_to_home`}
          onClick={() => history.push("/")}
        >
          {`Back to Home`}
        </Button>
      </Grid>
    </Grid>
  );
};

// Removed classes from propTypes as it's not passed but generated by hook.
Confirmation.propTypes = {
  history: PropTypes.object,
};

export default Confirmation;
